CREATE TABLE REPLE_TBL(
    C_code number PRIMARY key,
    B_code number,
    C_user VARCHAR2(20) NOT NULL,
    C_comment VARCHAR2(1000) NOT NULL,
    C_password VARCHAR2(10) NOT NULL,
    C_regDate DATE NOT NULL
    );

CREATE SEQUENCE REPLE_SEQ
NOCACHE;   

INSERT INTO REPLE_TBL VALUES ( REPLE_SEQ.NEXTVAL, 1, 'ASDF', '내용내용', '1234', SYSDATE);

COMMIT;

SELECT * FROM REPLE_TBL;